# Generated by Django 3.0.5 on 2021-07-09 19:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('mobileno', models.CharField(max_length=13, null=True)),
                ('qualification', models.CharField(max_length=255, null=True)),
                ('applyfor', models.CharField(max_length=255, null=True)),
                ('img', models.FileField(default='', upload_to='carrerimg')),
                ('createdon', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Products Category',
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('mobileno', models.CharField(max_length=13, null=True)),
                ('messages', models.TextField(null=True)),
                ('createdon', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_tittle', models.CharField(default='', max_length=255)),
                ('doctor_cover_image', models.ImageField(default='', upload_to='doctor_doc/cover_img')),
                ('doctor_description', models.TextField(null=True)),
                ('doctor_documet', models.FileField(default='', upload_to='doctor_doc/doc')),
            ],
            options={
                'verbose_name_plural': 'Doctor Document',
                'ordering': ['doctor_tittle'],
            },
        ),
        migrations.CreateModel(
            name='Doctor_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_name', models.CharField(default='', max_length=255)),
                ('dc_img', models.ImageField(default='', upload_to='doctor_slider')),
            ],
            options={
                'verbose_name_plural': 'Doctor Slider',
                'ordering': ['dc_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_tittle', models.CharField(default='', max_length=255)),
                ('employee_cover_image', models.ImageField(default='', upload_to='employee_doc/cover_img')),
                ('employee_description', models.TextField(null=True)),
                ('employee_documet', models.FileField(default='', upload_to='employee_doc/doc')),
            ],
            options={
                'verbose_name_plural': 'Employee Document',
                'ordering': ['employee_tittle'],
            },
        ),
        migrations.CreateModel(
            name='Employee_Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ep_name', models.CharField(default='', max_length=255)),
                ('ep_img', models.ImageField(default='', upload_to='employee_slider')),
            ],
            options={
                'verbose_name_plural': 'Employee Slider',
                'ordering': ['ep_name'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=255, null=True)),
                ('gallery_img', models.ImageField(default='', upload_to='Gallery_img')),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['gallery_img'],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, null=True)),
                ('testimonial', models.TextField(max_length=355, null=True)),
                ('user_img', models.ImageField(default='', upload_to='testimonial_user_img')),
            ],
            options={
                'verbose_name_plural': 'Testimonial',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User_Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_tittle', models.CharField(default='', max_length=255)),
                ('user_cover_image', models.ImageField(default='', upload_to='user_doc/cover_img')),
                ('user_description', models.TextField(null=True)),
                ('user_documet', models.FileField(default='', upload_to='user_doc/doc')),
            ],
            options={
                'verbose_name_plural': 'User Document',
                'ordering': ['user_tittle'],
            },
        ),
        migrations.CreateModel(
            name='User_Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('phoneno', models.CharField(max_length=13)),
                ('doc_messages', models.TextField(max_length=55555, null=True)),
                ('products', models.ManyToManyField(blank=True, to='first_app.Product_Order')),
            ],
            options={
                'verbose_name_plural': 'Doctor PO',
                'ordering': ['doctor_name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_tittle', models.CharField(default='', max_length=255)),
                ('product_details', models.TextField(default='', max_length=255)),
                ('product_price', models.IntegerField(default='')),
                ('product_cat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['product_tittle'],
            },
        ),
        migrations.AddField(
            model_name='product_order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='first_app.Products'),
        ),
        migrations.CreateModel(
            name='DoctorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobileno', models.CharField(blank=True, max_length=13, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('education_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_img', models.ImageField(blank=True, default='', upload_to='doctor_registration')),
                ('profile_img', models.ImageField(blank=True, default='', upload_to='doctor_profile')),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('doc_about', models.CharField(blank=True, max_length=500, null=True)),
                ('user_type', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('DOCTOR', 'Doctor')], default='EMPLOYEE', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Add Doctor & Employee',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
